export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const TOGGLE_ERROR_MESSAGE = 'TOGGLE_ERROR_MESSAGE';
export const TOGGLE_MODAL_VISIBILITY = 'TOGGLE_MODAL_VISIBILITY';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
